name: Bug Report
description: Let us know something is wrong
title: "[Bug]: "
labels: ["bug"]
body:
- type: checkboxes
  id: preflight-check
  attributes:
    label: Before you create this bug report, please make sure that
    options:
      - label: Checked that the issue isn't already filed
        required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected Behavior
    description: Please provide a consise description of what you're expecting.
  validations:
    required: true
- type: textarea
  id: current-behavior
  attributes:
    label: Current Behavior
    description: A consise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce this behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Info
    description: |
      Links, references, pretty much anything that will give us more context about the issue you are encountering!
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
