name: Feature Request
description: Have a cool idea?
title: "[Feature]: "
labels: ["enhancement"]
body:
- type: checkboxes
  id: preflight-check
  attributes:
    label: Before you create this feature enhancement report, please make sure that
    options:
      - label: Checked that the issue isn't already filed
        required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected Behavior
    description: Please provide a consise description of what you're expecting.
    placeholder: A description of the problem you are trying to solve, including why you think it is a problem
  validations:
    required: true
- type: textarea
  id: current-behavior
  attributes:
    label: Current Behavior
    description: A consise description of what you're experiencing.
    placeholder: A description of the current behavior, including workarounds or alternative solutions you might considered
  validations:
    required: true
- type: textarea
  attributes:
    label: Solution Overview
    description: An overview of the suggested solution
    placeholder: |
     Describe how your solution would work, in as many details as possible
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Info
    description: |
      Links, references, pretty much anything that will give us more context about the issue you are encountering!
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
