name: Build workflow for push

on:
  push:
    branches: [feature/*]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build:
    runs-on: [windows-latest]
    strategy:
      matrix:
        dotnet: ['5.0.x'] 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Risotto
    - name: Build
      run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
      working-directory: Risotto
