name: CI

on:
  push:
    branches:
      - develop
      - Risotto-Coverage
  
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: [windows-latest]
    strategy:
      matrix:
        dotnet: ['5.0.x'] 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies
      run: dotnet restore Risotto.sln
    - name: Build
      run: dotnet build --no-restore
      working-directory: Risotto
    - name: Test
      run: dotnet test --no-build --verbosity normal
           /p:CollectCoverage=true
           /p:CoverletOutput=TestResults/
           /p:CoverletOutputFormat=lcov
      working-directory: Risotto.Test
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./Risotto.Tests/TestResults/coverage.info 
